# Generated by Django 5.2.15 on 2026-06-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], max_length=20)),
                ('deliverability', models.CharField(choices=[('Inbox', 'Inbox'), ('Spam Folder', 'Spam Folder'), ('Pending', 'Pending')], max_length=20)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
