# Generated by Django 5.2.15 on 2026-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='emaillog',
            old_name='last_activity',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='deliverability',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Spam', 'Spam'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Read', 'Read')], default='Sent', max_length=20),
        ),
    ]
